# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fc2aa972c967016ccddb21123ae0fdf302986eb748e0d3ebf7c7af63557d0b5eeaddc6a93ac41b56c49a9a6afe544101138fd4eefef880fb10a691c3ecde36af

test:
  secret_key_base: a0b969e11a4be5417c27d46d397ae88e18ab1c6cf01df9b9e7fed2c9a0c6fe4e6fe331b37a3712bdd52eb2fca2bd2b092a2c6e612da62fa7709f8adb31a7f6ea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
